/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankGUI;

/**
 *
 * @author offic
 */
public class AccountDetails extends javax.swing.JDialog {

    /**
     * Creates new form AccountDetails
     */
    public AccountDetails(java.awt.Frame parent, boolean modal, Customer customer) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        
       setTitle(String.format("Account details - %s %s", customer.getFirstName(), customer.getLastName()));
       FirstNameData.setText( customer.getFirstName());
       LastNameData.setText( customer.getLastName());
       nidData.setText(customer.getNid());
       AccountTypeData.setText(customer.getAccount().getAccountType());
       AccountNumberData.setText(String.valueOf(customer.getAccount().getAccountNumber()));
       BalanceData.setText(String.format("%.2f", customer.getAccount().getBalance()));
       InterestData.setText(String.format("%.2f",customer.getAccount().getInterest()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstNameLabel = new javax.swing.JLabel();
        FirstNameData = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        LastNameData = new javax.swing.JLabel();
        nidLabel = new javax.swing.JLabel();
        nidData = new javax.swing.JLabel();
        AccountNumberLabel = new javax.swing.JLabel();
        AccountNumberData = new javax.swing.JLabel();
        AccountTypeLabel = new javax.swing.JLabel();
        AccountTypeData = new javax.swing.JLabel();
        BalanceLabel = new javax.swing.JLabel();
        BalanceData = new javax.swing.JLabel();
        interestRateLabel = new javax.swing.JLabel();
        InterestData = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(240, 250));
        getContentPane().setLayout(new java.awt.GridLayout(8, 2, 4, 5));

        FirstNameLabel.setText("  First Name:");
        getContentPane().add(FirstNameLabel);
        getContentPane().add(FirstNameData);

        LastNameLabel.setText("  Last Name:");
        getContentPane().add(LastNameLabel);
        getContentPane().add(LastNameData);

        nidLabel.setText("  NID:");
        getContentPane().add(nidLabel);
        getContentPane().add(nidData);

        AccountNumberLabel.setText("  Account Number:");
        getContentPane().add(AccountNumberLabel);
        getContentPane().add(AccountNumberData);

        AccountTypeLabel.setText("  Account  Type:");
        getContentPane().add(AccountTypeLabel);
        getContentPane().add(AccountTypeData);

        BalanceLabel.setText("  Balance:");
        getContentPane().add(BalanceLabel);
        getContentPane().add(BalanceData);

        interestRateLabel.setText("  Interest rate:");
        getContentPane().add(interestRateLabel);
        getContentPane().add(InterestData);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNumberData;
    private javax.swing.JLabel AccountNumberLabel;
    private javax.swing.JLabel AccountTypeData;
    private javax.swing.JLabel AccountTypeLabel;
    private javax.swing.JLabel BalanceData;
    private javax.swing.JLabel BalanceLabel;
    private javax.swing.JLabel FirstNameData;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel InterestData;
    private javax.swing.JLabel LastNameData;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel interestRateLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nidData;
    private javax.swing.JLabel nidLabel;
    // End of variables declaration//GEN-END:variables
}
