/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankGUI;

import javax.swing.JOptionPane;

/**
 *
 * @author offic
 */
public class withdrawMenu extends javax.swing.JDialog {

    private final Customer customer;
    
    /**
     * Creates new form depositMenu
     */
    public withdrawMenu(java.awt.Frame parent, boolean modal, Customer customer) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.customer = customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        withdrawLabel = new javax.swing.JLabel();
        withdrawFields = new javax.swing.JTextField();
        withdrawCllick = new javax.swing.JButton();
        withdrawCancelClick = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Withdraw");
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        withdrawLabel.setText(" Withdrawal amount");
        getContentPane().add(withdrawLabel);

        withdrawFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawFieldsActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawFields);

        withdrawCllick.setText("Withdraw");
        withdrawCllick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawCllickActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawCllick);

        withdrawCancelClick.setText("Cancel");
        getContentPane().add(withdrawCancelClick);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawFieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawFieldsActionPerformed

    private void withdrawCllickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawCllickActionPerformed
        StringBuilder warnings = new StringBuilder();
        if(withdrawFields.getText().isEmpty()){
            warnings.append("Amount cannot be empty!");
        }
        else {
            double amount = 0;
            
            try  {
                amount = Double.parseDouble(withdrawFields.getText());
                
                    if(amount > customer.getAccount().getBalance()){
                        warnings.append("Insufficant funds!");
                    }
                
                else {
                    int result = JOptionPane.showConfirmDialog(this, "Withdraw "+ amount + "BDT from this account?\n"
                    + "Charge: "+ String.format("%.2f",customer.getAccount().getInterest()/100 *amount)+ " BDT");
                        if(result == JOptionPane.OK_OPTION){
                            customer.getAccount().withdraw(amount);
                            this.dispose();
                        }
                }
                
            }
            catch(NumberFormatException ex){
                warnings.append("withdraw amount is not number");
            }
        }
        if(warnings.length() > 0){
            JOptionPane.showMessageDialog(this,warnings.toString(), "Withdraw failed", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_withdrawCllickActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton withdrawCancelClick;
    private javax.swing.JButton withdrawCllick;
    private javax.swing.JTextField withdrawFields;
    private javax.swing.JLabel withdrawLabel;
    // End of variables declaration//GEN-END:variables
}
